### PR TITLE
(WIP) New ML "Shap" image: `slalomggp/shap`

### PR DESCRIPTION
**Pull request by aaronsteers**

### CODE REVIEW

**Comment by aaronsteers** [comment]
@jacksandom - I haven't made this generic in terms of integrating with Terraform, but instead I've just created a new folder in this repo where I'm managing other Docker containers. I created a `README.md` which shows how to build and test the image locally. Once it's ready to go, we can push to dockerhub and reference in the ML Ops Infra Catalog item.

**Comment by aaronsteers** [comment]
Here's the readme - much easier to read here than in the native Markdown:

https://github.com/slalom-ggp/dataops-tools/tree/feat/shap/containers/docker-mlops

**Comment by aaronsteers** [comment]
I've tested successfully that the image builds, runs, parses input variables, and prints the basic log outputs.

**Comment by jacksandom** [comment]
Hi @aaronsteers, thanks for this - unfortunately i'm running into a problem at the first hurdle. When I run 'docker build' I get a SSL: CERTIFICATE_VERIFY_FAILED error on RUN pip install shap.

Did you run into anything like this?

**Comment by jacksandom** [comment]
Opening new branch for SageMaker 'bring your own model'

**Pull request closed without merging**
